---
# defaults file for php

php_packages:
  - php
  - libapache2-mod-php
  - php-cli
  - php-dev
  - php-mbstring
  - php-mcrypt
  - php-mysql
  - php-gd
  - php-curl
  - php-zip
php_ini:
  date.timezone: UTC
  default_charset: UTF-8
  mbstring.language: neutral
  mbstring.internal_encoding: UTF-8
  post_max_size: 10M # Same with VVV
  short_open_tag: Off
  upload_max_filesize: 10M # Same with VVV
  memory_limit: 512M
